config/routes.rb
Rails.application.routes.draw do
 
 root 'posts#index'
 
 resources :posts
 
end

app/models/post.rb
class Post < ActiveRecord::Base
    
    has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100#" }
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    
    def index
        @posts = Post.all
    end
    
    def show
        @post = Post.find(params[:id])
    end
    
    def create
        @post = Post.create(post_params)
        if @post.save
            redirect_to posts_path
        else
            render 'new'
        end
    end
    
    def new
         @post = Post.new
    end
    
    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to posts_path
    end
    
    private
    def post_params
        params.require(:post).permit(:title, :post, :image)
    end
    
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class = "container">
<%= yield %>
</div>

</body>
</html>

app/views/posts/index.html.erb
<h1>Posts</h1>


<% @posts.each do |a| %>


<%= image_tag a.image.url(:thumb) %><br>
<%= a.title %><br>
<%= a.post %><br>

<%= link_to 'Show Post', post_path(a) %><br>


<%= link_to "X", post_path(a), method: :delete, data: {confirm: "Are You Sure?"} %><br><br>




<% end %>

<hr>

<div class = "btn btn-success"><%= link_to 'New', new_post_path() %></div>

app/views/posts/new.html.erb
<%= form_for @post, html: { multipart: true } do |a| %>

<%= a.label :image %><br>
<%= a.file_field :image %><br>

<%= a.label :title %><br>
<%= a.text_field :title %><br>

<%= a.label :post %><br>
<%= a.text_area :post %><br>

<%= a.submit %><br>

<% end %>

app/views/posts/show.html.erb
<h1>Post Being Viewed: <%= @post.title %></h1><br>


<%= image_tag @post.image.url(:medium) %><br>
<p><%= @post.post %></p><br>

<hr>
<%= link_to 'Home', posts_path() %>